services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
        - net 

  redis:
    image: redis:8-alpine
    container_name: redis
    volumes:
      - cache-data:/data
    ports:
      - 6379:6379
    networks:
      - net

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200:3200
    volumes:
      - tracer-data:/var/tempo
    networks:
      - net

  project:
    build:
      context: ..
      dockerfile: ./scripts/Dockerfile
    depends_on: 
      - postgres
      - redis
    env_file:
      - ../.env
    ports:
      - 8080:8080
    networks:
      - net


volumes:
  data:
  cache-data:
  tracer-data:

networks:
  net:
