services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
        - net 

  redis:
    image: redis:8-alpine
    container_name: redis
    volumes:
      - cache-data:/data
    ports:
      - 6379:6379
    networks:
      - net

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200:3200
      - 4318:4318
    volumes:
      - tracer-data:/var/tempo
      - ./tempo.yaml:/etc/tempo.yaml
    command: -config.file=/etc/tempo.yaml
    networks:
      - net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=local
      - GF_SECURITY_ADMIN_PASSWORD=local
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - net
    depends_on:
      - tempo

  project:
    build:
      context: ..
      dockerfile: ./scripts/Dockerfile
    depends_on: 
      - postgres
      - redis
      - tempo
    env_file:
      - ../.env
    ports:
      - 8080:8080
    networks:
      - net


volumes:
  data:
  cache-data:
  tracer-data:
  grafana-data:

networks:
  net:
